<a href="https://colab.research.google.com/github/FanaticsKang/first_dp_step/blob/main/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
import torch.nn as nn
import numpy as np
from PIL import Image
from matplotlib import pyplot as plt

def main():
  data = [[1, 2],[3, 4]]
  x_data = torch.tensor(data)
  print(x_data.type())

  np_array = np.array(data)
  x_np = torch.from_numpy(np_array)
  print(x_np.type())

  x_ones = torch.ones_like(x_data)
  print(f"Ones Tensor: \n {x_ones} \n")

  x_rand = torch.rand_like(x_data, dtype=torch.float)
  print(f"Random Tensor: \n {x_rand} \n")

  shape = (2,3)
  rand_tensor = torch.rand(shape)
  ones_tensor = torch.ones(shape)
  zeros_tensor = torch.zeros(shape)
  print(f"Random Tensor: \n {rand_tensor} \n")
  print(f"Ones Tensor: \n {ones_tensor} \n")
  print(f"Zeros Tensor: \n {zeros_tensor}")

  tensor = torch.rand(3,4)

  print(f"Shape of tensor: {tensor.shape}")
  print(f"Datatype of tensor: {tensor.dtype}")
  print(f"Device tensor is stored on: {tensor.device}")


if __name__ == '__main__':
    main()

torch.LongTensor
torch.LongTensor
Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7574, 0.8178],
        [0.5795, 0.8855]]) 

Random Tensor: 
 tensor([[0.5680, 0.1473, 0.4355],
        [0.6801, 0.9185, 0.3247]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
